apiRules:
  - exclude:
      uidRegex: Sexiled.Updater
      type: Namespace
  - exclude:
      uidRegex: Sexiled.Example
      type: Namespace
  - exclude:
      uidRegex: Sexiled.CreditTags
      type: Namespace
